// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"kratos-chatroom/app/chatroom/internal/conf"
	"kratos-chatroom/app/chatroom/internal/server"
	"kratos-chatroom/app/chatroom/internal/service"
)

// Injectors from wire.go:

// initApp init kratos application.
func initApp(confServer *conf.Server, registry *conf.Registry, auth *conf.Auth, logger log.Logger) (*kratos.App, func(), error) {
	chatRoomService := service.NewChatRoomService(logger)
	websocketServer := server.NewWebsocketServer(confServer, logger, chatRoomService)
	registrar := server.NewRegistrar(registry)
	app := newApp(logger, websocketServer, registrar)
	return app, func() {
	}, nil
}
