cd ./app/message || exit
CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o ./bin/message ./...
cd ../../
cd ./app/user || exit
CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o ./bin/user ./...
docker-compose up --build