server:
  rest:
    addr: "0.0.0.0:7788"
    timeout: 10s
    enable_swagger: true
    enable_pprof: true
    cors:
      headers:
        - "X-Requested-With"
        - "Content-Type"
        - "Authorization"
      methods:
        - "GET"
        - "POST"
        - "PUT"
        - "DELETE"
        - "HEAD"
        - "OPTIONS"
      origins:
        - "*"
    middleware:
      auth:
        method: "HS256"
        key: "some_api_key"

  grpc:
    addr: "0.0.0.0:0"
    timeout: 10s
    middleware:

  asynq:
    endpoint: "localhost:6379"
    password: "123456"
    db: 1

client:
  grpc:
    timeout: 10s
    middleware:
      enable_logging: true
      enable_recovery: true
      enable_tracing: true
      enable_validate: true
      enable_circuit_breaker: true
      auth:
        method: ""
        key: "some_api_key"
