{
 "title": "LGTM Demo",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "QPS",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(server_requests_code_total[1m]))by(operation) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "App request time duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, rate(server_requests_seconds_bucket_seconds_bucket[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "App logs",
   "type": "logs",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "{filename=\"app.log\"}| json"
    }
   ]
  },
  {
   "title": "CPU Profiling",
   "type": "flamegraph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 31 },
   "targets": [
    {
     "labelSelector": "{instance=\"app:6060\"}",
     "profileTypeId": "process_cpu:cpu:nanoseconds:cpu:nanoseconds"
    }
   ]
  }
 ]
}