// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"kratos-monolithic-demo/app/admin/service/internal/data/ent/dictdetail"
	"kratos-monolithic-demo/app/admin/service/internal/data/ent/predicate"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// DictDetailQuery is the builder for querying DictDetail entities.
type DictDetailQuery struct {
	config
	ctx        *QueryContext
	order      []dictdetail.OrderOption
	inters     []Interceptor
	predicates []predicate.DictDetail
	modifiers  []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the DictDetailQuery builder.
func (ddq *DictDetailQuery) Where(ps ...predicate.DictDetail) *DictDetailQuery {
	ddq.predicates = append(ddq.predicates, ps...)
	return ddq
}

// Limit the number of records to be returned by this query.
func (ddq *DictDetailQuery) Limit(limit int) *DictDetailQuery {
	ddq.ctx.Limit = &limit
	return ddq
}

// Offset to start from.
func (ddq *DictDetailQuery) Offset(offset int) *DictDetailQuery {
	ddq.ctx.Offset = &offset
	return ddq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (ddq *DictDetailQuery) Unique(unique bool) *DictDetailQuery {
	ddq.ctx.Unique = &unique
	return ddq
}

// Order specifies how the records should be ordered.
func (ddq *DictDetailQuery) Order(o ...dictdetail.OrderOption) *DictDetailQuery {
	ddq.order = append(ddq.order, o...)
	return ddq
}

// First returns the first DictDetail entity from the query.
// Returns a *NotFoundError when no DictDetail was found.
func (ddq *DictDetailQuery) First(ctx context.Context) (*DictDetail, error) {
	nodes, err := ddq.Limit(1).All(setContextOp(ctx, ddq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{dictdetail.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (ddq *DictDetailQuery) FirstX(ctx context.Context) *DictDetail {
	node, err := ddq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first DictDetail ID from the query.
// Returns a *NotFoundError when no DictDetail ID was found.
func (ddq *DictDetailQuery) FirstID(ctx context.Context) (id uint32, err error) {
	var ids []uint32
	if ids, err = ddq.Limit(1).IDs(setContextOp(ctx, ddq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{dictdetail.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (ddq *DictDetailQuery) FirstIDX(ctx context.Context) uint32 {
	id, err := ddq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single DictDetail entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one DictDetail entity is found.
// Returns a *NotFoundError when no DictDetail entities are found.
func (ddq *DictDetailQuery) Only(ctx context.Context) (*DictDetail, error) {
	nodes, err := ddq.Limit(2).All(setContextOp(ctx, ddq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{dictdetail.Label}
	default:
		return nil, &NotSingularError{dictdetail.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (ddq *DictDetailQuery) OnlyX(ctx context.Context) *DictDetail {
	node, err := ddq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only DictDetail ID in the query.
// Returns a *NotSingularError when more than one DictDetail ID is found.
// Returns a *NotFoundError when no entities are found.
func (ddq *DictDetailQuery) OnlyID(ctx context.Context) (id uint32, err error) {
	var ids []uint32
	if ids, err = ddq.Limit(2).IDs(setContextOp(ctx, ddq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{dictdetail.Label}
	default:
		err = &NotSingularError{dictdetail.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (ddq *DictDetailQuery) OnlyIDX(ctx context.Context) uint32 {
	id, err := ddq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of DictDetails.
func (ddq *DictDetailQuery) All(ctx context.Context) ([]*DictDetail, error) {
	ctx = setContextOp(ctx, ddq.ctx, "All")
	if err := ddq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*DictDetail, *DictDetailQuery]()
	return withInterceptors[[]*DictDetail](ctx, ddq, qr, ddq.inters)
}

// AllX is like All, but panics if an error occurs.
func (ddq *DictDetailQuery) AllX(ctx context.Context) []*DictDetail {
	nodes, err := ddq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of DictDetail IDs.
func (ddq *DictDetailQuery) IDs(ctx context.Context) (ids []uint32, err error) {
	if ddq.ctx.Unique == nil && ddq.path != nil {
		ddq.Unique(true)
	}
	ctx = setContextOp(ctx, ddq.ctx, "IDs")
	if err = ddq.Select(dictdetail.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (ddq *DictDetailQuery) IDsX(ctx context.Context) []uint32 {
	ids, err := ddq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (ddq *DictDetailQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, ddq.ctx, "Count")
	if err := ddq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, ddq, querierCount[*DictDetailQuery](), ddq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (ddq *DictDetailQuery) CountX(ctx context.Context) int {
	count, err := ddq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (ddq *DictDetailQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, ddq.ctx, "Exist")
	switch _, err := ddq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (ddq *DictDetailQuery) ExistX(ctx context.Context) bool {
	exist, err := ddq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the DictDetailQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (ddq *DictDetailQuery) Clone() *DictDetailQuery {
	if ddq == nil {
		return nil
	}
	return &DictDetailQuery{
		config:     ddq.config,
		ctx:        ddq.ctx.Clone(),
		order:      append([]dictdetail.OrderOption{}, ddq.order...),
		inters:     append([]Interceptor{}, ddq.inters...),
		predicates: append([]predicate.DictDetail{}, ddq.predicates...),
		// clone intermediate query.
		sql:  ddq.sql.Clone(),
		path: ddq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreateTime time.Time `json:"create_time,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.DictDetail.Query().
//		GroupBy(dictdetail.FieldCreateTime).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (ddq *DictDetailQuery) GroupBy(field string, fields ...string) *DictDetailGroupBy {
	ddq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &DictDetailGroupBy{build: ddq}
	grbuild.flds = &ddq.ctx.Fields
	grbuild.label = dictdetail.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreateTime time.Time `json:"create_time,omitempty"`
//	}
//
//	client.DictDetail.Query().
//		Select(dictdetail.FieldCreateTime).
//		Scan(ctx, &v)
func (ddq *DictDetailQuery) Select(fields ...string) *DictDetailSelect {
	ddq.ctx.Fields = append(ddq.ctx.Fields, fields...)
	sbuild := &DictDetailSelect{DictDetailQuery: ddq}
	sbuild.label = dictdetail.Label
	sbuild.flds, sbuild.scan = &ddq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a DictDetailSelect configured with the given aggregations.
func (ddq *DictDetailQuery) Aggregate(fns ...AggregateFunc) *DictDetailSelect {
	return ddq.Select().Aggregate(fns...)
}

func (ddq *DictDetailQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range ddq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, ddq); err != nil {
				return err
			}
		}
	}
	for _, f := range ddq.ctx.Fields {
		if !dictdetail.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if ddq.path != nil {
		prev, err := ddq.path(ctx)
		if err != nil {
			return err
		}
		ddq.sql = prev
	}
	return nil
}

func (ddq *DictDetailQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*DictDetail, error) {
	var (
		nodes = []*DictDetail{}
		_spec = ddq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*DictDetail).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &DictDetail{config: ddq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	if len(ddq.modifiers) > 0 {
		_spec.Modifiers = ddq.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, ddq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (ddq *DictDetailQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := ddq.querySpec()
	if len(ddq.modifiers) > 0 {
		_spec.Modifiers = ddq.modifiers
	}
	_spec.Node.Columns = ddq.ctx.Fields
	if len(ddq.ctx.Fields) > 0 {
		_spec.Unique = ddq.ctx.Unique != nil && *ddq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, ddq.driver, _spec)
}

func (ddq *DictDetailQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(dictdetail.Table, dictdetail.Columns, sqlgraph.NewFieldSpec(dictdetail.FieldID, field.TypeUint32))
	_spec.From = ddq.sql
	if unique := ddq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if ddq.path != nil {
		_spec.Unique = true
	}
	if fields := ddq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, dictdetail.FieldID)
		for i := range fields {
			if fields[i] != dictdetail.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := ddq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := ddq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := ddq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := ddq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (ddq *DictDetailQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(ddq.driver.Dialect())
	t1 := builder.Table(dictdetail.Table)
	columns := ddq.ctx.Fields
	if len(columns) == 0 {
		columns = dictdetail.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if ddq.sql != nil {
		selector = ddq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if ddq.ctx.Unique != nil && *ddq.ctx.Unique {
		selector.Distinct()
	}
	for _, m := range ddq.modifiers {
		m(selector)
	}
	for _, p := range ddq.predicates {
		p(selector)
	}
	for _, p := range ddq.order {
		p(selector)
	}
	if offset := ddq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := ddq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// Modify adds a query modifier for attaching custom logic to queries.
func (ddq *DictDetailQuery) Modify(modifiers ...func(s *sql.Selector)) *DictDetailSelect {
	ddq.modifiers = append(ddq.modifiers, modifiers...)
	return ddq.Select()
}

// DictDetailGroupBy is the group-by builder for DictDetail entities.
type DictDetailGroupBy struct {
	selector
	build *DictDetailQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (ddgb *DictDetailGroupBy) Aggregate(fns ...AggregateFunc) *DictDetailGroupBy {
	ddgb.fns = append(ddgb.fns, fns...)
	return ddgb
}

// Scan applies the selector query and scans the result into the given value.
func (ddgb *DictDetailGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, ddgb.build.ctx, "GroupBy")
	if err := ddgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*DictDetailQuery, *DictDetailGroupBy](ctx, ddgb.build, ddgb, ddgb.build.inters, v)
}

func (ddgb *DictDetailGroupBy) sqlScan(ctx context.Context, root *DictDetailQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(ddgb.fns))
	for _, fn := range ddgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*ddgb.flds)+len(ddgb.fns))
		for _, f := range *ddgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*ddgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := ddgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// DictDetailSelect is the builder for selecting fields of DictDetail entities.
type DictDetailSelect struct {
	*DictDetailQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (dds *DictDetailSelect) Aggregate(fns ...AggregateFunc) *DictDetailSelect {
	dds.fns = append(dds.fns, fns...)
	return dds
}

// Scan applies the selector query and scans the result into the given value.
func (dds *DictDetailSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, dds.ctx, "Select")
	if err := dds.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*DictDetailQuery, *DictDetailSelect](ctx, dds.DictDetailQuery, dds, dds.inters, v)
}

func (dds *DictDetailSelect) sqlScan(ctx context.Context, root *DictDetailQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(dds.fns))
	for _, fn := range dds.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*dds.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := dds.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// Modify adds a query modifier for attaching custom logic to queries.
func (dds *DictDetailSelect) Modify(modifiers ...func(s *sql.Selector)) *DictDetailSelect {
	dds.modifiers = append(dds.modifiers, modifiers...)
	return dds
}
