trace:
  endpoint: http://127.0.0.1:14268/api/traces
server:
  http:
    addr: 0.0.0.0:0
    timeout: 1s
  grpc:
    addr: 0.0.0.0:0
    timeout: 1s
  kafka:
    addrs:
      - localhost:9092
data:
  database:
    driver: postgres
    source: host=localhost port=5432 user=postgres password=123456 dbname=postgres sslmode=disable
  redis:
    addr: 127.0.0.1:6379
    read_timeout: 0.2s
    write_timeout: 0.2s