// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.19.1
// source: admin.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// AdminClient is the client API for Admin service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AdminClient interface {
	//
	GetOrganizations(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetOrganizationsReply, error)
	//
	GetGeofences(ctx context.Context, in *GetGeofencesReq, opts ...grpc.CallOption) (*GetGetGeofencesReply, error)
	//
	GetPositionsHistory(ctx context.Context, in *GetPositionsHistoryReq, opts ...grpc.CallOption) (*GetPositionsHistoryReply, error)
}

type adminClient struct {
	cc grpc.ClientConnInterface
}

func NewAdminClient(cc grpc.ClientConnInterface) AdminClient {
	return &adminClient{cc}
}

func (c *adminClient) GetOrganizations(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetOrganizationsReply, error) {
	out := new(GetOrganizationsReply)
	err := c.cc.Invoke(ctx, "/admin.v1.Admin/GetOrganizations", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminClient) GetGeofences(ctx context.Context, in *GetGeofencesReq, opts ...grpc.CallOption) (*GetGetGeofencesReply, error) {
	out := new(GetGetGeofencesReply)
	err := c.cc.Invoke(ctx, "/admin.v1.Admin/GetGeofences", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminClient) GetPositionsHistory(ctx context.Context, in *GetPositionsHistoryReq, opts ...grpc.CallOption) (*GetPositionsHistoryReply, error) {
	out := new(GetPositionsHistoryReply)
	err := c.cc.Invoke(ctx, "/admin.v1.Admin/GetPositionsHistory", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AdminServer is the server API for Admin service.
// All implementations must embed UnimplementedAdminServer
// for forward compatibility
type AdminServer interface {
	//
	GetOrganizations(context.Context, *emptypb.Empty) (*GetOrganizationsReply, error)
	//
	GetGeofences(context.Context, *GetGeofencesReq) (*GetGetGeofencesReply, error)
	//
	GetPositionsHistory(context.Context, *GetPositionsHistoryReq) (*GetPositionsHistoryReply, error)
	mustEmbedUnimplementedAdminServer()
}

// UnimplementedAdminServer must be embedded to have forward compatible implementations.
type UnimplementedAdminServer struct {
}

func (UnimplementedAdminServer) GetOrganizations(context.Context, *emptypb.Empty) (*GetOrganizationsReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetOrganizations not implemented")
}
func (UnimplementedAdminServer) GetGeofences(context.Context, *GetGeofencesReq) (*GetGetGeofencesReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetGeofences not implemented")
}
func (UnimplementedAdminServer) GetPositionsHistory(context.Context, *GetPositionsHistoryReq) (*GetPositionsHistoryReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPositionsHistory not implemented")
}
func (UnimplementedAdminServer) mustEmbedUnimplementedAdminServer() {}

// UnsafeAdminServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AdminServer will
// result in compilation errors.
type UnsafeAdminServer interface {
	mustEmbedUnimplementedAdminServer()
}

func RegisterAdminServer(s grpc.ServiceRegistrar, srv AdminServer) {
	s.RegisterService(&Admin_ServiceDesc, srv)
}

func _Admin_GetOrganizations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).GetOrganizations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/admin.v1.Admin/GetOrganizations",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).GetOrganizations(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Admin_GetGeofences_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGeofencesReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).GetGeofences(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/admin.v1.Admin/GetGeofences",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).GetGeofences(ctx, req.(*GetGeofencesReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Admin_GetPositionsHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPositionsHistoryReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).GetPositionsHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/admin.v1.Admin/GetPositionsHistory",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).GetPositionsHistory(ctx, req.(*GetPositionsHistoryReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Admin_ServiceDesc is the grpc.ServiceDesc for Admin service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Admin_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "admin.v1.Admin",
	HandlerType: (*AdminServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetOrganizations",
			Handler:    _Admin_GetOrganizations_Handler,
		},
		{
			MethodName: "GetGeofences",
			Handler:    _Admin_GetGeofences_Handler,
		},
		{
			MethodName: "GetPositionsHistory",
			Handler:    _Admin_GetPositionsHistory_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "admin.proto",
}
