name: Go

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        go: [ 1.16, 1.17 ]
    name: build & test
    runs-on: ubuntu-latest
    services:
      etcd:
        image: gcr.io/etcd-development/etcd:v3.5.0
        ports:
          - 2379:2379
        env:
          ETCD_LISTEN_CLIENT_URLS: http://0.0.0.0:2379
          ETCD_ADVERTISE_CLIENT_URLS: http://0.0.0.0:2379
      consul:
        image: consul:latest
        ports:
          - 8500:8500
      nacos:
        image: nacos/nacos-server:latest
        env:
          MODE: standalone
        ports:
          - "8848:8848"
          - "9848:9848"
      polaris:
        image: houseme/polaris-server-with-config:latest
        ports:
          - 8090:8090
          - 8091:8091
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
      - name: Examples
        run: |
          go build ./...
          go test ./...
